name: Release

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    uses: ./.github/workflows/check.yml

  build-release:
    needs: check
    permissions:
      contents: write
    uses: charlieh0tel/deb-workflows/.github/workflows/rust-build-exes.yml@v1
    with:
      build-deps: libdbus-1-dev